abuseipdb.settings:
  type: config_object
  label: 'AbuseIPDB Settings'
  mapping:
    abuseipdb:
      type: mapping
      mapping:
        api_key:
          type: text
          label: 'AbuseIPDB Api Key'
        forms:
          type: string
          label: 'Forms which are checked'
        forms_ban_ip:
          type: boolean
          label: 'Ban abusive IPs during form validation'
        last_check:
          type: integer
          label: 'Timestamp of the last API check'
        last_report:
          type: integer
          label: 'Timestamp of last API report'
        paths:
          type: string
          label: 'List of paths targeted by exploitative IPs'
        paths_ban_ip:
          type: boolean
          label: 'Ban abusive IPs which hit specified Drupal paths'
        shutdown:
          type: boolean
          label: 'Emergency shutdown'
